---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release
  namespace: envoy-gateway
spec:
  interval: 15m
  chart:
    spec:
      interval: 24h
      chart: gateway-helm
      version: "v1.1.2"
      sourceRef:
        kind: HelmRepository
        name: envoy
        namespace: flux-system
  values:
