[project]
name = "infra"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pyinfra>=3.1.1",
]

[tool.uv]
dev-dependencies = [
    "pylsp-mypy>=0.6.9",
    "python-lsp-ruff>=2.2.2",
    "python-lsp-server>=1.12.0",
]
