#!/usr/bin/env fish
argparse --name=__run 'c/capture' -- $argv; or exit 1

set line_clear '\r\33[2k'

# show job to be run
if not test "$_flag_capture" = ""; tput sc; end
printf "%s[-] \$ $argv%s" \
    (set_color -o white) (set_color normal)
if test "$_flag_capture" = ""
    printf "\n"
end

# run job
set buf (mktemp)
if not test "$_flag_capture" = ""
    fish -c "$argv" &>$buf
else
    fish -c "$argv"
end

# output status, and if capturing stdout/stderr
if test $status = "0"
    if not test "$_flag_capture" = ""
        tput rc; printf $line_clear
    end
    printf "%s[✔] \$ $argv%s\n" \
        (set_color -o green) (set_color normal)
else
    if not test "$_flag_capture" = ""
        tput rc; printf $line_clear
    end
    printf "%s[✘] \$ $argv\n%s" \
        (set_color -o red) (set_color normal)
    if not test "$_flag_capture" = ""
        cat $buf
    end
    exit 1
end
