#!/usr/bin/fish
# mise description="Run ansible playbooks"
source (which __cd) "$root/ansible"

if not which ansible &>/dev/null
    __run -- pip install ansible
end

__run -- ansible-playbook -i inventory.ini nodes.yaml
