#!/usr/bin/fish
# mise description="Apply manifests to kubernetes"
# mise depends=["proxy"]
source (which __cd) "$root/manifests"

set argocd_manifest "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/core-install.yaml"

# argocd
__section --title argocd
if not kubectl get namespace argocd &>/dev/null
    __run -c -- kubectl create namespace argocd
    __run -c -- kubectl -n argocd apply -f argocd-config.yaml
    __run -c -- kubectl -n argocd apply -f $argocd_manifest
else
    __run -c -- kubectl -n argocd apply -f argocd-config.yaml
end


# argocd apps (manifests/**/app.yaml)
__section --title "argocd apps"
# ensure git is synced as apps generally rely on being
# able to read additional manifests from github
if not __is_git_synced
    __warning -- git is not synced with remote
    exit 1
end
for yaml in (fd -d2 app.yaml)
    __k_apply -f $yaml
end
