#!/usr/bin/env fish
# mise description="Build static sites"
source (which __cd) "$root/static"

if not which htmlmin &>/dev/null
    __run -- pip install htmlmin
end

for dir in (fd -t directory -d 1 -E 'build' . | xargs -L 1 basename)
    __section --title $dir

    if not test -e build/$dir
        __run -c -- mkdir build/$dir
    end

    for content_file in (fd -t file '' $dir)
        __run -c -- "esh base.esh content_file=$content_file | htmlmin > build/$content_file"
    end
end
