#!/usr/bin/fish
# mise description="Run tofu apply"
source (which __cd) "$root/tofu"

set keys \
    "CLOUDFLARE_API_TOKEN" \
    "CLOUDFLARE_R2_TOKEN" \
    "CLOUDFLARE_R2_ACCESS_KEY_ID" \
    "CLOUDFLARE_R2_ACCESS_KEY_SECRET"\
    "DIGITALOCEAN_TOKEN" \
    "VULTR_API_KEY"
for key in $keys
    set -x "$key" "op://Infra/$key/credential"
end

set -x AWS_ACCESS_KEY_ID "$CLOUDFLARE_R2_ACCESS_KEY_ID"
set -x AWS_SECRET_ACCESS_KEY "$CLOUDFLARE_R2_ACCESS_KEY_SECRET"

if not test -e .terraform
    op run -- __run -c tofu init
end

set args "apply"
if not test "$argv" = ""
    set args "$argv"
end

op run -- __run tofu $args
