#!/usr/bin/fish
# mise description="Run tofu apply"
source (which __cd) "$root/tofu"

if not op item get "infra env" --fields notesPlain --format json &>/dev/null
    __warning -- "`op signin | source` required"
    exit 1
end
op item get "infra env" --fields notesPlain --format json \
    | jq ".value" -r \
    | source

if not test -e .terraform
    __run -c tofu init
end

set args "apply"
if not test "$argv" = ""
    set args "$argv"
end

__run tofu $args
