[[a]]
name = "echo"
content = "${data.terraform_remote_state.platform.outputs.n0_vk_idte_net}"

[email.protonmail]
verification = "cd73f4126457b725c3ca6086e6dc7414a5fdcb98"
domain_key = "d3gsjlavtfqwpxmoh5buz367dfgyvmi6rvhxctanstw4vzgaaoruq"
