FROM alpine:3 AS build

ARG NGINX_VERSION="1.25.3"
ARG NGINX_CHECKSUM="64c5b975ca287939e828303fa857d22f142b251f17808dfe41733512d9cded86"
ARG NGINX_CONFIG="\
    --sbin-path=/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --pid-path=/tmp/nginx.pid \
    --http-log-path=/dev/stdout \
    --error-log-path=/dev/stdout \
    --http-client-body-temp-path=/tmp/client_temp \
    --http-proxy-temp-path=/tmp/proxy_temp \
    --http-fastcgi-temp-path=/tmp/fastcgi_temp \
    --http-uwsgi-temp-path=/tmp/uwsgi_temp \
    --http-scgi-temp-path=/tmp/scgi_temp \
    --with-file-aio \
    --with-threads \
    --without-http_gzip_module \
    --without-http_rewrite_module"

ADD https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz /tmp/nginx.tar.gz

RUN cd /tmp && \
    if [ "$NGINX_CHECKSUM" != "$(sha256sum /tmp/nginx.tar.gz | awk '{print $1}')" ]; then exit 1; fi && \
    tar xf /tmp/nginx.tar.gz && \
    mv /tmp/nginx-$NGINX_VERSION /tmp/nginx

RUN cd /tmp/nginx && \
    apk add git gcc g++ perl make linux-headers upx binutils && \
    ./configure $NGINX_CONFIG && \
    make && \
    strip /tmp/nginx/objs/nginx && \
    upx -9 /tmp/nginx/objs/nginx

FROM scratch

COPY /containers/static-sites/rootfs /
COPY /containers/static-sites/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /lib/ld-musl-x86_64.so.1 /lib/
COPY --from=build /tmp/nginx/objs/nginx /nginx

COPY /static/build /sites/

STOPSIGNAL SIGTERM
ENTRYPOINT ["/nginx", "-g", "daemon off;"]
