---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy
  namespace: flux-system
spec:
  interval: 24h
  type: oci
  url: oci://registry-1.docker.io/envoyproxy
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: goauthentik
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.goauthentik.io
