---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo
    spec:
      containers:
      - name: echo
        image: docker.io/hashicorp/http-echo:latest
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo-svc
  namespace: echo
spec:
  selector:
    app.kubernetes.io/name: echo
  ports:
  - protocol: TCP
    port: 5678
    targetPort: 5678
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-route
  namespace: echo
spec:
  parentRefs:
  - name: envoy-gateway
    namespace: envoy-gateway
    sectionName: https-echo
  hostnames:
  - "echo.idletea.net"
  rules:
  - filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        set:
        - name: strict-transport-security
          value: "max-age=63072000; includeSubDomains; preload"
    backendRefs:
    - name: echo-svc
      port: 5678
