apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsvplease-dev
  namespace: rsvplease-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      # this is actually ignored
      # https://github.com/rancher/local-path-provisioner?tab=readme-ov-file#cons
      storage: 1Gi
