name: build static-sites
on:
  push:
    branches:
      - trunk
    paths:
      - containers/static-sites/**
      - static/**
env:
  REGISTRY: ghcr.io
  NAMESPACE: idletea
  IMAGE: static-sites
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build templates
        run: |
          pip install jinja2 minify_html \
            && python3 static/build.py
      - name: login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}
      - name: build and publish
        uses: docker/build-push-action@v5
        with:
          context: "."
          file: "containers/static-sites/Containerfile"
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}:latest
          push: true
